version: '3.9'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: crm_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: ./django-crm
    command: gunicorn crm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django-crm:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  mysql-data:
